---
- name: Install pyenv dependencies
  ansible.builtin.apt:
    name:
     - make
     - build-essential
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - wget
     - curl
     - llvm
     - libncursesw5-dev
     - xz-utils
     - tk-dev
     - libxml2-dev
     - libxmlsec1-dev
     - libffi-dev
     - liblzma-dev
    state: present
    update_cache: true

- name: Download pyenv script
  ansible.builtin.get_url:
    dest: /tmp/pyenv.sh
    url: https://pyenv.run
    mode: "0555"

- name: Execute pyenv install script
  shell:
    cmd: /tmp/pyenv.sh
    creates: "{{ home_dir }}/.pyenv"

- name: Create a directory
  ansible.builtin.file:
    path: /root/test_pyenv
    state: directory

- name: Check if Python 3.7.7 is already installed
  shell: "{{ pyenv_dir }} versions | grep -q '3.7.7'"
  register: python_3_7_7_installed
  changed_when: false
  ignore_errors: true  

- name: Check if Python 3.10.4 is already installed
  shell: "{{ pyenv_dir }} versions | grep -q '3.10.4'"
  register: python_3_10_4_installed
  changed_when: false
  ignore_errors: true    

- name: Install Python 3.7.7 using pyenv
  ansible.builtin.shell:
    cmd: |
      {{ pyenv_dir }} install 3.7.7
  when: python_3_7_7_installed.rc != 0    

- name: Install Python 3.10.4 using pyenv
  ansible.builtin.shell:
    cmd: |
      {{ pyenv_dir }} install 3.10.4
  when: python_3_10_4_installed.rc != 0    

- name: Install pyenv locally for specific directory
  ansible.builtin.shell:
    chdir: /root/test_pyenv
    cmd: | 
      {{ pyenv_dir }} local 3.7.7

- name: Install pyenv globally
  ansible.builtin.shell:
    cmd: | 
      {{ pyenv_dir }} global 3.10.4
  

