---
- hosts: aws_ec2
  gather_facts: true
  become: true
  roles:
    - pyenv
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: sujata-static-website-one
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300
    